name: flutter_rollbar
description: Rollbar reporting for flutter
version: 0.0.3
authors:
- Twin Sun, LLC <admin@twinsunsolutions.com>
- Jami Couch <jami.couch@twinsunsolutions.com>
homepage: https://github.com/twinsunllc/flutter_rollbar

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: '>=0.4.2+4 <2.0.0'
  package_info: ^0.4.1
  requests: ^3.3.0